#!/usr/bin/env bash
# Wire mica in as the system file picker, via xdg-desktop-portal-termfilechooser.
# After this, portal-aware apps (Firefox/zen, VS Code, Flatpaks…) open mica when
# they ask you to choose a file. Re-runnable. `setup.sh --revert` undoes it.
set -eu

repo="$(cd -- "$(dirname -- "$(realpath -- "$0")")/.." && pwd)"
wrapper="$repo/portal/mica-filechooser.sh"
cfg_home="${XDG_CONFIG_HOME:-$HOME/.config}"
tfc_dir="$cfg_home/xdg-desktop-portal-termfilechooser"
xdp_dir="$cfg_home/xdg-desktop-portal"

desktop="$(printf '%s' "${XDG_CURRENT_DESKTOP:-}" | cut -d: -f1 | tr '[:upper:]' '[:lower:]')"
# Write both the desktop-specific conf AND the generic portals.conf. The portal's
# systemd service often lacks XDG_CURRENT_DESKTOP, so it can only find the generic
# one; the desktop-specific file covers sessions where it IS set.
portals_confs=("$xdp_dir/portals.conf")
[ -n "$desktop" ] && portals_confs+=("$xdp_dir/$desktop-portals.conf")

if [ "${1:-}" = "--revert" ]; then
    for pc in "${portals_confs[@]}"; do
        [ -f "$pc" ] || continue
        # drop just our FileChooser override, leave the rest of the file intact
        sed -i '/^org\.freedesktop\.impl\.portal\.FileChooser=termfilechooser$/d' "$pc"
        echo "removed the mica FileChooser override from $pc"
    done
    systemctl --user restart xdg-desktop-portal.service 2>/dev/null || true
    echo "reverted — file dialogs fall back to your previous backend (gtk/kde)."
    exit 0
fi

chmod +x "$wrapper"

# 1. the termfilechooser backend has to be installed (it provides the .portal)
have_backend=""
for d in /usr/share /usr/lib /usr/local/share /usr/local/lib; do
    [ -f "$d/xdg-desktop-portal/portals/termfilechooser.portal" ] && have_backend=1
done
if [ -z "$have_backend" ]; then
    echo "!! xdg-desktop-portal-termfilechooser isn't installed."
    echo "   Arch:   paru -S xdg-desktop-portal-termfilechooser   (hunkyburrito fork)"
    echo "   others: https://github.com/hunkyburrito/xdg-desktop-portal-termfilechooser"
    exit 1
fi

# 2. point termfilechooser's picker command at the mica wrapper
mkdir -p "$tfc_dir"
cat > "$tfc_dir/config" <<EOF
# generated by mica portal/setup.sh — mica is the file picker command
[filechooser]
cmd=$wrapper
default_dir=$HOME
create_help_file=0
open_mode=suggested
save_mode=suggested
EOF
echo "wrote $tfc_dir/config"

# 3. route ONLY the FileChooser interface to termfilechooser; keep every other
#    portal (screenshare, etc.) on whatever you already use. We copy your existing
#    default= line so we don't change anything else.
mkdir -p "$xdp_dir"
sys_conf="/usr/share/xdg-desktop-portal/${desktop:+$desktop-}portals.conf"
[ -f "$sys_conf" ] || sys_conf="/usr/share/xdg-desktop-portal/portals.conf"
default_line="$(grep -E '^default=' "$sys_conf" 2>/dev/null | head -1 || true)"
[ -n "$default_line" ] || default_line="default=gtk"
for pc in "${portals_confs[@]}"; do
    cat > "$pc" <<EOF
[preferred]
$default_line
org.freedesktop.impl.portal.FileChooser=termfilechooser
EOF
    echo "wrote $pc"
done

# 4. reload the portal so the new routing takes effect
systemctl --user restart xdg-desktop-portal.service 2>/dev/null || true

cat <<'EOF'

✓ mica is now the file picker for portal-aware apps.

One more step per app — some draw their own dialog unless told to use the portal:
  • Firefox / zen : about:config → widget.use-xdg-desktop-portal.file-picker = 2
  • GTK apps      : run with  GTK_USE_PORTAL=1
  • Electron/VS Code, Flatpaks : usually already use the portal on Wayland

Test it: open any app and try to upload/open a file — mica should appear.
Undo anytime:  portal/setup.sh --revert
EOF
